Website/views.py
# This file is going to store all of the main views or the URL end points for the actual 
# functioning front end aspect of our website

# Store default roots for website

from flask import Blueprint, render_template, request, flash, jsonify, redirect
from flask_login import login_required, current_user
from .models import Note
from . import db
import json


# Setup blueprint for Flask application
views = Blueprint('views', __name__)


@views.route('/notes', methods=['GET', 'POST'])
# Now you can not get to the home page, unless you are login
# This function will whenever we go to the slash route 
def notes():
    if request.method == 'POST':
        note = request.form.get('note')
        if len(note) < 1:
            flash('Note is too short!', category='error')
        else:
            new_note = Note(data=note, user_id=current_user.id)
            db.session.add(new_note)
            db.session.commit()
            flash('Note added!', category='success')

    # We will be able to check, if we have authenticated
    return render_template("notes.html", user=current_user)

@views.route('/delete-note', methods=['POST'])
def delete_note():
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()

    return jsonify({})

# Decorator are an elegent way to extend functionality of our original function, without altering their source code.
# '/' --> route
@views.route('/', methods=['GET', 'POST'])
# Now you can not get to the home page, unless you are login
# This function will whenever we go to the slash route 
def home():
    # We will be able to check, if we have authenticated
    return render_template("home.html", user=current_user)


@views.route('/menu', methods=['GET', 'POST'])
def menu():
    return render_template("menu.html", user=current_user)

@views.route('/contact', methods=['GET', 'POST'])
def contact():
    return render_template("contact.html", user=current_user)

@views.route('/cart', methods=['GET', 'POST'])
def add_to_cart():
    return render_template("cart.html", user=current_user)

@views.route('/home_EST', methods=['GET', 'POST'])
# Now you can not get to the home page, unless you are login
# This function will whenever we go to the slash route 
def home_EST():
    # We will be able to check, if we have authenticated
    return render_template("home_EST.html", user=current_user)

@views.route('/contact_EST', methods=['GET', 'POST'])
# Now you can not get to the home page, unless you are login
# This function will whenever we go to the slash route 
def contact_EST():
    # We will be able to check, if we have authenticated
    return render_template("contact_EST.html", user=current_user)

@views.route('/menu_EST', methods=['GET', 'POST'])
# Now you can not get to the home page, unless you are login
# This function will whenever we go to the slash route 
def menu_EST():
    # We will be able to check, if we have authenticated
    return render_template("menu_EST.html", user=current_user)

@views.route('/home_RUS', methods=['GET', 'POST'])
# Now you can not get to the home page, unless you are login
# This function will whenever we go to the slash route 
def home_RUS():
    # We will be able to check, if we have authenticated
    return render_template("home_RUS.html", user=current_user)

@views.route('/menu_RUS', methods=['GET', 'POST'])
# Now you can not get to the home page, unless you are login
# This function will whenever we go to the slash route 
def menu_RUS():
    # We will be able to check, if we have authenticated
    return render_template("menu_RUS.html", user=current_user)

@views.route('/contact_RUS', methods=['GET', 'POST'])
# Now you can not get to the home page, unless you are login
# This function will whenever we go to the slash route 
def contact_RUS():
    # We will be able to check, if we have authenticated
    return render_template("contact_RUS.html", user=current_user)

Website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" >
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description"
          content="Welcome to bakingfox, your go-to destination for fresh bakery. Our platform offers a user-friendly experience, and a vast array of pastry. Explore our website today and discover why bakingfox is the perfect choice for you!"/>
    <meta name="keywords" content="Bakery, Destination, Goods" />
    <meta name="author" content="Vladislav Paskevits" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no">
    <link rel="shortcut icon" type="image/png" href="assets/favicon.png" >

    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous"/>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          crossorigin="anonymous"/>
    <link rel="shortcut icon"
          href="{{ url_for('static', filename='favicon.ico') }}"/>
    <link rel="stylesheet"
          type="text/css"
          href="{{ url_for('static',filename='styles/base.css') }}"/>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <script type="text/javascript"
            src="{{ url_for('static', filename='index.js') }}"></script>
    <title>
      {% block title %}
        Home
      {% endblock title %}
    </title>
  </head>
  <body>
    <div class="header-top">
      <ul class="header-languages">
        <ul class="language-switcher-locale-url">
          <li class="en">
            <a href="{{ url_for('views.home') }}">ENG</a>
          </li>
          <li class="ee">
            <a href="{{ url_for('views.home_EST') }}">EST</a>
          </li>
          <li class="ru">
            <a href="{{ url_for('views.home_RUS') }}">RUS</a>
          </li>
        </ul>
      </ul>
      <ul class="header-icons">
        <li>
          <a target="_blank"
             rel="noopener noreferrer"
             href="https://www.facebook.com/vlad.paskevits">
            <i class="fa fa-facebook">
            </i>
          </a>
        </li>
        <li>
          <a target="_blank"
             rel="noopener noreferrer"
             href="https://www.linkedin.com/in/vladislav-pa%C5%A1kevit%C5%A1-295b7823a/">
            <i class="fa fa-linkedin">
            </i>
          </a>
        </li>
        <li>
          <a target="_blank"
             rel="noopener noreferrer"
             href="https://github.com/Vladislp/Ginger-Baker-Web-Application">
            <i class="fa fa-github">
            </i>
          </a>
        </li>
      </ul>
    </div>
    <div class="header-bottom">
      <a class="header-logo"href="{{ url_for('views.home') }}">
        <img src="https://i.pinimg.com/736x/e2/c7/09/e2c709bbf86bef7787d16018785d15db.jpg"
             alt="Logo"
             height=""
             width=""/>
      </a>
      <nav class="header-navigation">
        <ul class="header-navigation-ul">
          <li>
            <a href="{{ url_for('views.home') }}">About</a>
          </li>
          <li>
            <a href="{{ url_for('views.menu') }}">Menu</a>
          </li>
          <li>
            <a href="{{ url_for('views.contact') }}">Contact</a>
          </li>
        </ul>
      </nav>
    </div>
    {% with messages = get_flashed_messages(with_categories=true) %}
      <!--We loop now all messages and show them in the page-->
      {% if messages %}
        {% for category, message in messages %}
          {% if category == 'error' %}
            <!--Display the message, whatever it is-->
            <div class="alert alert-dark alter-dismissable fade show"
                 role="alert"
                 style="position:absolute;
                        left: 20%;
                        transform: translate(-50%, 30%)">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">×</span>
              </button>
            </div>
          {% else %}
            <div class="alert alert-dark alter-dismissable fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">×</span>
              </button>
            </div>
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endwith %}
    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>
  </body>
</html>

Website/templates/base_EST.html
<!DOCTYPE html>
<html lang="est">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description"
          content="Avastage rebase pagar abil uus võimaluste maailm. Meie platvorm pakub parima kvaliteediga toote ja on loodud selleks, et muuta kõigile kättesaadavamaks. Olenemata sellest, kas olete kogenud professionaal või uudishimulik algaja , rebase pagar sisaldab kõike, mida edu saavutamiseks vajate. Tutvuge meie toodetega juba täna!"/>
    <meta name="keywords" content="Pagariäri, Sihtkoht, Kaubad" />
    <meta name="author" content="Vladislav Paskevits" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" >
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no">
    <link rel="shortcut icon" type="image/png" href="assets/favicon.png" >

    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous"/>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          crossorigin="anonymous"/>
    <link rel="shortcut icon"
          href="{{ url_for('static', filename='favicon.ico') }}"/>
    <link rel="stylesheet"
          type="text/css"
          href="{{ url_for('static',filename='styles/base.css') }}"/>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
          integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
          crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
          integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
          crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
          integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
          crossorigin="anonymous"></script>
    <script type="text/javascript"
          src="{{ url_for('static', filename='index.js') }}"></script>
    <title>
      {% block title %}
        Base
      {% endblock title %}
    </title>
  </head>
  <body>
    <div class="header-top">
      <ul class="header-languages">
        <ul class="language-switcher-locale-url">
          <li class="en">
            <a href="{{ url_for('views.home') }}">ENG</a>
          </li>
          <li class="ee">
            <a href="{{ url_for('views.home_EST') }}">EST</a>
          </li>
          <li class="ru">
            <a href="{{ url_for('views.home_RUS') }}">RUS</a>
          </li>
        </ul>
      </ul>
      <ul class="header-icons">
        <li>
          <a target="_blank"
             rel="noopener noreferrer"
             href="https://www.facebook.com/vlad.paskevits">
            <i class="fa fa-facebook">
            </i>
          </a>
        </li>
        <li>
          <a target="_blank"
             rel="noopener noreferrer"
             href="https://www.linkedin.com/in/vladislav-pa%C5%A1kevit%C5%A1-295b7823a/">
            <i class="fa fa-linkedin">
            </i>
          </a>
        </li>
        <li>
          <a target="_blank"
             rel="noopener noreferrer"
             href="https://github.com/Vladislp/Ginger-Baker-Web-Application">
            <i class="fa fa-github">
            </i>
          </a>
        </li>
        <li>
        </li>
      </ul>
    </div>
    <div class="header-bottom">
      <a class="header-logo"href="{{ url_for('views.home_EST') }}">
        <img src="https://i.pinimg.com/736x/e2/c7/09/e2c709bbf86bef7787d16018785d15db.jpg"
             alt="Logo"
             height=""
             width=""/>
      </a>
      <nav class="header-navigation">
        <ul class="header-navigation-ul">
          <li>
            <a href="{{ url_for('views.home_EST') }}">Meist</a>
          </li>
          <li>
            <a href="{{ url_for('views.menu_EST') }}">Menu</a>
          </li>
          <li>
            <a href="{{ url_for('views.contact_EST') }}">Võta ühendust</a>
          </li>
        </ul>
      </nav>
    </div>
  {% with messages = get_flashed_messages(with_categories=true) %}
    <!--We loop now all messages and show them in the page-->
    {% if messages %}
      {% for category, message in messages %}
        {% if category == 'error' %}
          <!--Display the message, whatever it is-->
          <div class="alert alert-dark alter-dismissable fade show"
                 role="alert"
                 style="position:absolute;
                        left: 20%;
                        transform: translate(-50%, 30%)">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">×</span>
              </button>
            </div>
        {% else %}
          <div class="alert alert-dark alter-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">×</span>
            </button>
          </div>
        {% endif %}
      {% endfor %}
    {% endif %}
  {% endwith %}
  <div class="container">
    {% block content %}{% endblock content %}
  </div>
</body>
</html>

Website/templates/base_RUS.html
<!DOCTYPE html>
<html lang="rus">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description"
          content="«Найдите все, что вам нужно, и многое другое на пекарь лисенок. Наша платформа предлагает широкий выбор выпечки, тщательно отобранных для удовлетворения потребностей клиентов. С приверженностью к удовлетворению клиентов, мы уверены, что пекарь лисенок — идеальный выбор для всех, кто ищет домашнию выпечку. Посетите нас сегодня и откройте для себя возможности!»"/>
    <meta name="keywords" content="Пекарня, Место назначения, Товары" />
    <meta name="author" content="Владислав Пашкевич" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" >
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no">
    <link rel="shortcut icon" type="image/png" href="assets/favicon.png" >


    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous"/>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          crossorigin="anonymous"/>
    <link rel="shortcut icon"
          href="{{ url_for('static', filename='favicon.ico') }}"/>
    <link rel="stylesheet"
          type="text/css"
          href="{{ url_for('static',filename='styles/base.css') }}"/>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <script type="text/javascript"
            src="{{ url_for('static', filename='index.js') }}"></script>
    <title>
      {% block title %}
        Home
      {% endblock title %}
    </title>
  </head>
  <body>
    <div class="header-top">
      <ul class="header-languages">
        <ul class="language-switcher-locale-url">
          <li class="en">
            <a href="{{ url_for('views.home') }}">ENG</a>
          </li>
          <li class="ee">
            <a href="{{ url_for('views.home_EST') }}">EST</a>
          </li>
          <li class="ru">
            <a href="{{ url_for('views.home_RUS') }}">RUS</a>
          </li>
        </ul>
      </ul>
      <ul class="header-icons">
        <li>
          <a target="_blank"
             rel="noopener noreferrer"
             href="https://www.facebook.com/vlad.paskevits">
            <i class="fa fa-facebook">
            </i>
          </a>
        </li>
        <li>
          <a target="_blank"
             rel="noopener noreferrer"
             href="https://www.linkedin.com/in/vladislav-pa%C5%A1kevit%C5%A1-295b7823a/">
            <i class="fa fa-linkedin">
            </i>
          </a>
        </li>
        <li>
          <a target="_blank"
             rel="noopener noreferrer"
             href="https://github.com/Vladislp/Ginger-Baker-Web-Application">
            <i class="fa fa-github">
            </i>
          </a>
        </li>
      </ul>
    </div>
    <div class="header-bottom">
      <a class="header-logo"href="{{ url_for('views.home_RUS') }}">
        <img src="https://i.pinimg.com/736x/e2/c7/09/e2c709bbf86bef7787d16018785d15db.jpg"
             alt="Logo"
             height=""
             width=""/>
      </a>
      <nav class="header-navigation">
        <ul class="header-navigation-ul">
          <li>
            <a href="{{ url_for('views.home_RUS') }}">О нас</a>
          </li>
          <li>
            <a href="{{ url_for('views.menu_RUS') }}">Меню</a>
          </li>
          <li>
            <a href="{{ url_for('views.contact_RUS') }}">Контакт</a>
          </li>
        </ul>
      </nav>
    </div>
    {% with messages = get_flashed_messages(with_categories=true) %}
      <!--We loop now all messages and show them in the page-->
      {% if messages %}
        {% for category, message in messages %}
          {% if category == 'error' %}
            <!--Display the message, whatever it is-->
            <div class="alert alert-dark alter-dismissable fade show"
                 role="alert"
                 style="position:absolute;
                        left: 20%;
                        transform: translate(-50%, 30%)">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">×</span>
              </button>
            </div>
          {% else %}
            <div class="alert alert-dark alter-dismissable fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">×</span>
              </button>
            </div>
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endwith %}
    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>
  </body>
</html>

Website/templates/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <!--Facebook Open Graph (Google)-->
	  <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content=
        "Go to fox baker and discover the world of home baking. 
        We offer the highest quality homemade baked goods for you, all in one place." 
    />
    <meta name="keywords" content="Welcome, Bakery, Sweets, BananaBread" />
    <meta name="author" content="Vladislav Paskevits" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge" >
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no">
    <link rel="shortcut icon" type="image/png" href="assets/favicon.png" >

    <!--Facebook Open Graph (Facebook)-->
    <meta property="og:title" content="Menu" />
    <meta property="og:type" content="webpage" />
    <meta property="og:image" content="goods" />
    <meta property="og:url" content="" />
    <meta property="og:description" content="" />

    <title>{% block title %} About {% endblock title %} </title>

    <link
    rel="stylesheet"
    type="text/css"
    href="{{ url_for('static',filename='styles/home.css') }}"
    />
  </head>

  {% extends "base.html" %}

  {% block content %}
  
  <body>
    <div class="container">
        <div class="header">
          <h1>Welcome to Our Dreamy Fox Bakery & Cafe</h1>
          <p>Fresh Baked Goodies Made with Love</p>
        </div>
    </div>
    
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <img src="bakery-shop-image.jpg" alt="" height="" width="" />
          </div>
          <div class="col-md-6">
            <h2>About Our Bakery</h2>
            <p>
              At our bakery, we believe that baking is an art form and a way to
              bring happiness to people's lives. We use only the freshest
              ingredients and take great care in crafting each and every one of
              our baked goods. From our classic cakes and pastries to our
              innovative desserts, there's something for everyone here at our
              bakery.
            </p>
            <a href="{{ url_for('views.menu') }}" class="btn btn-primary">View Our Menu</a>
          </div>
        </div>
      </div>

      <div class="featured">
        <h2>Featured Products</h2>
        <div class="row">
          <div class="col-md-4">
            <img
              src="https://cdn.pixabay.com/photo/2017/06/30/21/49/bread-2459926_1280.jpg"
              alt="Cake"
              height=""
              width=""
            />
            <h3>Delicious Cakes</h3>
            <p>
              Our cakes are made with love and only the freshest ingredients. Try
              one today!
            </p>
          </div>
          <div class="col-md-4">
            <img
              src="https://cdn.pixabay.com/photo/2016/05/10/09/14/cookies-1383304_1280.jpg"
              alt="Pastry"
              height=""
              width=""
            />
            <h3>Flaky Pastries</h3>
            <p>
              Flaky and buttery, our pastries are the perfect start to your day.
            </p>
          </div>
          <div class="col-md-4">
            <img
              src="https://cdn.pixabay.com/photo/2018/05/03/14/50/muffins-3371523_1280.jpg"
              alt="Dessert"
              height=""
              width=""
            />
            <h3>Innovative Desserts</h3>
            <p>
              Our desserts are always pushing the boundaries of what's possible in
              baking.
            </p>
          </div>
      </div>
    </div>

      <div class="footer">
        <p> Copyright © Foxy Bake</p>
      </div>
  </body>

  {% endblock content %}

</html>

Website/templates/home_EST.html
<!DOCTYPE html>
<html lang="est">
  <head>
    <meta charset="utf-8" />
    <!--Facebook Open Graph (Google)-->
	  <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content=
        "Nautige meie pagariäris värskelt küpsetatud tooteid ja maitsvaid hõrgutisi. 
        Klassikalistest sarvesaiadest kuni käsitööleivani – meil on igaühele midagi. 
        Külastage meid juba täna ja rahuldage oma magusaisu!" 
    />
    <meta name="keywords" content="Tere tulemast, Pagariäri, Maiustused, Banaanileib" />
    <meta name="author" content="Vladislav Paskevits" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge" >
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no">
    <link rel="shortcut icon" type="image/png" href="assets/favicon.png" >

    <!--Facebook Open Graph (Facebook)-->
    <meta property="og:title" content="Menu" />
    <meta property="og:type" content="webpage" />
    <meta property="og:image" content="goods" />
    <meta property="og:url" content="" />
    <meta property="og:description" content="" />

    <title>{% block title %} Meist {% endblock title %} </title>

    <link
    rel="stylesheet"
    type="text/css"
    href="{{ url_for('static',filename='styles/home.css') }}"
    />
  </head>

  {% extends "base_EST.html" %}

  {% block content %}

  <body>
    <div class="container">
        <div class="header">
          <h1>Tervitame teid meie Dreamy Fox Bakery & Cafe</h1>
          <p>Armastusega valmistatud värsked küpsetatud maiuspalad</p>
        </div>
    </div>
    
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <img src="bakery-shop-image.jpg" alt="" height="" width="" />
        </div>
        <div class="col-md-6">
          <h2>Meie pagariärist</h2>
          <p>
            Meie pagariäris usume, et küpsetamine on kunstivorm ja viis
            toovad inimeste ellu õnne. Kasutame ainult kõige värskemat
            koostisosad ja olge nende valmistamisel väga ettevaatlik
            meie küpsetised. Alates meie klassikalistest kookidest ja küpsetistest kuni meieni
            uuenduslikud magustoidud, meie kaupluses on igaühele midagi
            pagariäri.
          </p>
          <a href="{{ url_for('views.menu_EST') }}" class="btn btn-primary">Vaadake meie menu</a>
        </div>
      </div>
    </div>

    <div class="featured">
      <h2>Soovitatavad tooted</h2>
      <div class="row">
        <div class="col-md-4">
          <img
            src="https://cdn.pixabay.com/photo/2017/06/30/21/49/bread-2459926_1280.jpg"
            alt="Cake"
            width=""
            height=""
          />
          <h3>Maitsvad koogid</h3>
          <p>
            Meie koogid on valmistatud armastusega ja ainult kõige värskematest koostisosadest. Proovi
            üks täna!
          </p>
        </div>
        <div class="col-md-4">
          <img
            src="https://cdn.pixabay.com/photo/2016/05/10/09/14/cookies-1383304_1280.jpg"
            alt="Pastry"
            width=""
            height=""
          />
          <h3>Helbed küpsetised</h3>
          <p>
            Helbed ja võised – meie küpsetised on ideaalne algus teie päevale.
          </p>
        </div>
        <div class="col-md-4">
          <img
            src="https://cdn.pixabay.com/photo/2018/05/03/14/50/muffins-3371523_1280.jpg"
            alt="Dessert"
            width=""
            height=""
          />
          <h3>Uuenduslikud magustoidud</h3>
          <p>
            Meie magustoidud nihutavad alati võimaliku piire
            küpsetamine.
          </p>
        </div>
    </div>
  </div>

    <div class="footer">
      <p> Autoriõigus © Foxy Bake</p>
    </div>
</body>

{% endblock content %}
</html>